**Table of contents**<a id='toc0_'></a>    
- 1. [Python-Numpy](#toc1_)    
  - 1.1. [创建数组-array](#toc1_1_)    
    - 1.1.1. [从列表创建](#toc1_1_1_)    
    - 1.1.2. [从头创建](#toc1_1_2_)    
  - 1.2. [NumPy数组基础](#toc1_2_)    
    - 1.2.1. [属性ndim-shape-dtype](#toc1_2_1_)    
    - 1.2.2. [索引-[start:stop:step]](#toc1_2_2_)    
    - 1.2.3. [变形-np.reshape()](#toc1_2_3_)    
    - 1.2.4. [拼接-np.concatenate([...])](#toc1_2_4_)    
  - 1.3. [NumPy数组的计算：通用函数](#toc1_3_)    
      - 1.3.1.1. [算数运算](#toc1_3_1_1_)    
      - 1.3.1.2. [统计函数](#toc1_3_1_2_)    
  - 1.4. [数组的计算](#toc1_4_)    

<!-- vscode-jupyter-toc-config
	numbering=true
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

# 1. <a id='toc1_'></a>[Numpy概述](#toc0_)

- 优点：numpy可以完全替代python本身的统计部分，功能强大，方便有用；

- 缺点：不支持GPU计算

- 改进：可以用jax.numpy平替numpy

In [2]:
import numpy as np

## 1.1. <a id='toc1_1_'></a>[创建数组-array](#toc0_)

### 1.1.1. <a id='toc1_1_1_'></a>[从列表创建](#toc0_)

- np.array(object=[1, 2, 3], dtype=int, size=(3, 4))

In [3]:
# 创建一维数组
## 首先用列表推导式推到出一个列表
data_int = [i for i in range(1,10)]
print(data_int) 

# 不同于 Python 列表，NumPy 要求数组必须包含同一类型的数据。如果类型不匹配，NumPy 将会向上转换（如果可行）。
data_int_array = np.array(data_int, dtype=int)
print(data_int_array)

# 依据dtype指定数据类型
data_int2float_array = np.array(data_int, dtype=float)
print(data_int2float_array) 

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [5]:
# 创建二维数组
## 首先用列表推导式推到出一个列表
data_2d1 = [range(i, i+3) for i in [2, 4, 6]]; print(data_2d1)
data_2d2 = [[j for j in range(i, i+3)] for i in [2, 4, 6]]; print(data_2d2)

[range(2, 5), range(4, 7), range(6, 9)]
[[2, 3, 4], [4, 5, 6], [6, 7, 8]]


In [34]:
## 将列表传入arry中并指定dtype数据类型，创建数组
data_2d_array= np.array([range(i, i+3) for i in [2, 4, 6]], dtype=int); print(data_2d_array)
print(np.array(data_2d1, dtype=int))
print(np.array(data_2d2, dtype=int))

[[2 3 4]
 [4 5 6]
 [6 7 8]]
[[2 3 4]
 [4 5 6]
 [6 7 8]]
[[2 3 4]
 [4 5 6]
 [6 7 8]]


### 1.1.2. <a id='toc1_1_2_'></a>[从头创建](#toc0_)
- 面对大型数组的时候，用 NumPy 内置的方法从头创建数组是一种更高效的方法。以下是几个示例：

|函数名|注释|
|:-|:-|
|np.arrange()||
|np.zeros()||
|np.ones()||
|np.empty()||
|np.full()||
|np.linspace()||
|np.random.random()||
|np.random.normal()||
|np.random.randint()||
|np.eye()||

In [22]:
np.random.seed(0) # 设置随机数种子

In [23]:
# 创建一个长度为10的数组，数组的值都是0 
print('zeros', np.zeros(10, dtype=int) )
 # 创建一个3×5的数组，数组的值都是0 
print('zeros', np.zeros((3, 5), dtype=int) )

zeros [0 0 0 0 0 0 0 0 0 0]
zeros [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [24]:
# 创建一个3×5的浮点型数组，数组的值都是1 
print('ones', np.ones((3, 5), dtype=float))

ones [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
# 创建一个3×5的浮点型数组，数组的值都是3.14 
print('full', np.full((3, 5), 3.14))

full [[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [26]:
# 创建一个3×5的浮点型数组，数组的值是一个线性序列
# 从0开始，到20结束，步长为2 
# （它和内置的range()函数类似）
print('arange', np.arange(0, 20, 2))

arange [ 0  2  4  6  8 10 12 14 16 18]


In [14]:
# 创建一个5个元素的数组，这5个数均匀地分配到0~1 
print('linspace', np.linspace(0, 1, 5))

linspace [0.   0.25 0.5  0.75 1.  ]


In [21]:
# 创建一个3×3的、在0~1均匀分布的随机数组成的数组
print('random.random', np.random.random((3, 3)))

random.random [[0.069167   0.69742877 0.45354268]
 [0.7220556  0.86638233 0.97552151]
 [0.85580334 0.01171408 0.35997806]]


In [20]:
# 创建一个3×3的、均值为0、方差为1的
# 正态分布的随机数数组
print('random.normal', np.random.normal(0, 1, (3, 3)))

random.normal [[-0.37992245 -0.0457481   0.04989841]
 [-0.93553046  0.28738765  0.36042727]
 [ 0.40814812 -1.94071568  1.44483571]]


In [17]:
# 创建一个3×3的、[0, 10)区间的随机整型数组
print('random.randint', np.random.randint(0, 10, size=(3, 3)) )

random.randint [[6 3 6]
 [5 7 0]
 [8 4 6]]


In [18]:
# 创建一个3×3的单位矩阵
print('eye', np.eye(3))

eye [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# 创建一个由3个整型数组成的未初始化的数组
# 数组的值是内存空间中的任意值
print('empty', np.empty(3))

empty [1. 1. 1.]


## 1.2. <a id='toc1_2_'></a>[NumPy数组基础](#toc0_)
- 数组的属性
  - 确定数组的大小(ndim)、形状(shape)、存储大小(size)、数据类型(dtype)。
- 数组的索引
  - 获取和设置数组各个元素的值。
- 数组的切分
  - 在大的数组中获取或设置更小的子数组。
- 数组的变形
  - 改变给定数组的形状。
- 数组的拼接和分裂
  - 将多个数组合并为一个，以及将一个数组分裂成多个。

### 1.2.1. <a id='toc1_2_1_'></a>[属性ndim-shape-dtype](#toc0_)

In [40]:
import numpy as np 
np.random.seed(0) # 设置随机数种子
x1 = np.random.randint(10, size=6) # 一维数组
x2 = np.random.randint(10, size=(3, 4)) # 二维数组
x3 = np.random.randint(10, size=(3, 4, 5)) # 三维数组

# 数组的属性
print("x3 维度-ndim: ", x3.ndim) 
print("x3 形状-shape:", x3.shape) 
print("x3 大小（元素总个数）-size: ", x3.size)
print("数据类型-dtype:", x3.dtype)
print("每个数组元素字节大小-itemsize:", x3.itemsize, "bytes") 
print("数组总字节大小-nbytes:", x3.nbytes, "bytes") 

x3 维度-ndim:  3
x3 形状-shape: (3, 4, 5)
x3 大小（元素总个数）-size:  60
数据类型-dtype: int32
每个数组元素字节大小-itemsize: 4 bytes
数组总字节大小-nbytes: 240 bytes


### 1.2.2. <a id='toc1_2_2_'></a>[索引-[start:stop:step]](#toc0_)

In [36]:
print('-'*100)
# 数组的索引


----------------------------------------------------------------------------------------------------


In [48]:
print('-'*100)
# 数组的切分
# x[start:stop:step
np.arange(10), np.arange(10)[0:3]

----------------------------------------------------------------------------------------------------


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2]))

### 1.2.3. <a id='toc1_2_3_'></a>[变形-np.reshape()](#toc0_)

In [47]:
print('-'*100)
# 数组的变形
np.arange(10), np.arange(10).reshape((2, 5))

----------------------------------------------------------------------------------------------------


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

### 1.2.4. <a id='toc1_2_4_'></a>[拼接-np.concatenate([...])](#toc0_)

In [12]:
print('-'*100)
# 数组的拼接和分裂
x = np.arange(5)
y = np.arange(3)
z = np.arange(6)
x, y, z, np.concatenate( [x, y, z] )

----------------------------------------------------------------------------------------------------


(array([0, 1, 2, 3, 4]),
 array([0, 1, 2]),
 array([0, 1, 2, 3, 4, 5]),
 array([0, 1, 2, 3, 4, 0, 1, 2, 0, 1, 2, 3, 4, 5]))

In [19]:
x = np.arange(9).reshape((3,3))
y = np.arange(6).reshape((3,2))
z = np.arange(12).reshape((4,3))
x, y, z

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [22]:
np.concatenate([x,y], axis=1)
# np.concatenate([x,y]) # 默认是axis=0，会报错

array([[0, 1, 2, 0, 1],
       [3, 4, 5, 2, 3],
       [6, 7, 8, 4, 5]])

In [26]:
np.concatenate([x,z])
# np.concatenate([x,z], axis=1) # 维度不对应，会报错

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## 1.3. <a id='toc1_3_'></a>[数组的计算：通用函数](#toc0_)

#### 1.3.1.1. <a id='toc1_3_1_1_'></a>[算数运算](#toc0_)

|操作|函数名|
|:-|:-|
|+|np.add()|
|-|np.substract()|
|*|np.multiply()|
|/|np.divide()|
|%|取余 (9 % 4 = 1) |
|-|np.negative()|
|绝对值|np.absolute()|
|乘方|np.power()|
||np.exp()|
||np.exp2()|
||np.log()|
||np.log2()|
||np.log10()|
|三角函数|np.sin()|
||np.cos()|
||np.tan()|

In [41]:
# NumPy 通用函数的使用方式非常自然，因为它用到了 Python 原生的算术运算符，标准的加、减、乘、除都可以使用：
x = np.arange(4); print(x); print('-'*100)
print("x =", x) 
print("x + 5 =", x + 5, np.add(x, 5)) 
print("x - 5 =", x - 5, np.subtract(x, 5)) 
print("x * 2 =", x * 2, np.multiply(x, 2)) 
print("x / 2 =", x / 2, np.divide(x, 2)) 
print("x // 2 =", x // 2, np.floor_divide(x, 2)) #地板除法运算

[0 1 2 3]
----------------------------------------------------------------------------------------------------
x = [0 1 2 3]
x + 5 = [5 6 7 8] [5 6 7 8]
x - 5 = [-5 -4 -3 -2] [-5 -4 -3 -2]
x * 2 = [0 2 4 6] [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5] [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1] [0 0 1 1]


In [29]:
# 还有逻辑非、** 表示的指数运算符和 % 表示的模运算符的一元通用函数：
print("-x = ", -x, np.negative(x)) 
print("x ** 2 = ", x ** 2, np.power(x, 2)) 
print("x % 2 = ", x % 2, np.mod(x, 2))

-x =  [[ 0 -1 -2]
 [-3 -4 -5]
 [-6 -7 -8]] [[ 0 -1 -2]
 [-3 -4 -5]
 [-6 -7 -8]]
x ** 2 =  [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]] [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
x % 2 =  [[0 1 0]
 [1 0 1]
 [0 1 0]] [[0 1 0]
 [1 0 1]
 [0 1 0]]


In [30]:
# 你可以任意将这些算术运算符组合使用。当然，你得考虑这些运算符的优先级：
print(-(0.5*x + 1) ** 2, np.negative(np.power(np.add(np.multiply(x,0.5),1),2)))

[[ -1.    -2.25  -4.  ]
 [ -6.25  -9.   -12.25]
 [-16.   -20.25 -25.  ]] [[ -1.    -2.25  -4.  ]
 [ -6.25  -9.   -12.25]
 [-16.   -20.25 -25.  ]]


In [44]:
# 绝对值
print(np.absolute(x))

# 三角函数
theta = np.linspace(0, np.pi, 3)
print("theta = ", theta); print('-'*100)
print("sin(theta) = ", np.sin(theta)) 
print("cos(theta) = ", np.cos(theta)) 
print("tan(theta) = ", np.tan(theta))

# 指数和对数
x = [1, 2, 3]; print('-'*100)
print("x =", x) 
print("e^x =", np.exp(x)) 
print("2^x =", np.exp2(x)) 
print("3^x =", np.power(3, x))
print("x =", x) 
print("ln(x) =", np.log(x)) 
print("log2(x) =", np.log2(x)) 
print("log10(x) =", np.log10(x)) 

# 专用的通用函数
# 除了以上介绍到的，NumPy 还提供了很多通用函数，包括双曲三角函数、比特位运算、比
# 较运算符、弧度转化为角度的运算、取整和求余运算，等等。浏览 NumPy 的文档将会揭
# 示很多有趣的功能。

# 高级通用函数
## 指定输出
x = np.arange(5) 
y = np.empty(5) 
np.multiply(x, 10, out=y) 
print(y)
## 聚合
## 外积


[0 1 2 3]
theta =  [0.         1.57079633 3.14159265]
----------------------------------------------------------------------------------------------------
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
----------------------------------------------------------------------------------------------------
x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]
x = [1, 2, 3]
ln(x) = [0.         0.69314718 1.09861229]
log2(x) = [0.        1.        1.5849625]
log10(x) = [0.         0.30103    0.47712125]
[ 0. 10. 20. 30. 40.]


4

#### 1.3.1.2. <a id='toc1_3_1_2_'></a>[统计函数](#toc0_)
|函数名|注释|
|:-|:-|
|np.sum()|计算元素和|
|np.prod()|计算元素积|
|np.mean()|计算元素的平均值|
|np.std()|计算元素的标准差|
|np.var()|计算元素的方差|
|np.median()|计算元素的中位数|
|np.max()|找出最大值|
|np.argmax()|找出最大值的索引|
|np.min()|找出最小值|
|np.argmin()|找出最小值的索引|
|np.percentile()|计算基于元素排列的统计值|
|np.any()|验证任何一个元素是否为真|
|np.all()|验证所有元素是否为真|

In [28]:
np.sum(x) # 求和
np.min(x), np.max(x) # 最小值和最大值

(0, 8)

## 1.4. <a id='toc1_4_'></a>[数组的比较](#toc0_)

|运算符|对应通用函数|
|:-|:-|
|==|np.equal|
|!=|np.not_equal|
|<|np.less|
|<=|np.less_equal|
|>|np.greater|
|>=|np.greater_equal|

In [ ]:
# 广播

# 比较、掩码和布尔逻辑

